# Generated by Django 5.2.1 on 2025-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('subscription', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
