# Generated by Django 5.2.1 on 2025-11-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevideo',
            name='craftsman',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='proof_document',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='jobrequest',
            name='craftsman',
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='schedule',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
        migrations.DeleteModel(
            name='ServiceVideo',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='job',
        ),
    ]
