# Generated by Django 5.2.1 on 2025-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_craftsman_proof_document_craftsman_slug_serviceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
