# Generated by Django 5.2.1 on 2025-11-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_servicevideo_craftsman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='service_image',
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='craftsmen/service_images/')),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='api.craftsman')),
            ],
        ),
    ]
