# Generated by Django 5.2.1 on 2025-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_craftsman_description_alter_craftsman_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
