# Generated by Django 5.2.1 on 2025-11-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_craftsman_service_image_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='craftsmen/service_videos/')),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_videos', to='api.craftsman')),
            ],
        ),
    ]
