# Generated by Django 5.2.1 on 2025-11-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_service_image_servicevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
