# Generated by Django 5.2.1 on 2025-11-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_craftsman_service_image_delete_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='craftsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.craftsman'),
        ),
    ]
