# Generated by Django 5.2.1 on 2025-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobrequest_craftsman'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
