# Generated by Django 5.2.1 on 2025-11-20 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_craftsman_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='full_name',
        ),
    ]
