# Generated by Django 5.2.1 on 2025-05-23 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_craftsman_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='email',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='location',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=100),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
