# Generated by Django 5.2.1 on 2025-11-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_craftsman_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
