# Generated by Django 5.2.1 on 2026-01-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobrequest_budget_jobrequest_company_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='quote_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
