# Generated by Django 5.2.1 on 2026-02-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_jobrequest_quote_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
