# Generated by Django 5.2.1 on 2025-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_craftsman_is_approved_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
