# Generated by Django 5.2.1 on 2026-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_craftsman_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Quote Submitted', 'Quote Submitted'), ('Quote Approved', 'Quote Approved'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
