# Generated by Django 5.2.1 on 2026-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_jobrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='quote_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes/'),
        ),
    ]
