# Generated by Django 5.2.1 on 2026-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_jobrequest_quote_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='quote_approved_by_client',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
