# Generated by Django 5.2.1 on 2026-02-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_jobrequest_quote_approved_by_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_proofs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_images', to='api.jobrequest')),
            ],
        ),
    ]
