# Generated by Django 5.2.1 on 2026-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_contactmessage_email_alter_contactmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='proof_documents/'),
        ),
    ]
