# Generated by Django 5.2.1 on 2026-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_craftsman_proof_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='account_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('1-2 years', '1-2 years'), ('3-5 years', '3-5 years'), ('5-10 years', '5-10 years'), ('10+ years', '10+ years')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Free-text name when not in the standard choices list', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Price'), ('hour', 'Per Hour'), ('day', 'Per Day'), ('sqm', 'Per m²')], default='fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Roofing', 'Roofing'), ('Welding', 'Welding'), ('Tiling', 'Tiling'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Masonry', 'Masonry'), ('AC Repair', 'AC Repair'), ('Woodwork', 'Woodwork'), ('Auto Repair', 'Auto Repair')], max_length=255, null=True),
        ),
    ]
