# Generated by Django 5.2.1 on 2026-03-13 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_craftsman_account_type_craftsman_experience_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, help_text='Email address or phone number', max_length=255, null=True)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('link', 'Link')], default='email', max_length=20)),
                ('role', models.CharField(choices=[('helper', 'Helper'), ('foreman', 'Foreman'), ('partner', 'Partner')], default='helper', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending_invite', 'Invite Sent'), ('pending_approval', 'Awaiting Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending_invite', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='api.craftsman')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CraftsmanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(choices=[('helper', 'Helper'), ('foreman', 'Foreman'), ('partner', 'Partner')], default='helper', max_length=20)),
                ('status', models.CharField(choices=[('pending_approval', 'Awaiting Approval'), ('accepted', 'Active'), ('rejected', 'Rejected')], default='pending_approval', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.craftsman')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='craftsman_memberships', to=settings.AUTH_USER_MODEL)),
                ('invite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='api.teaminvite')),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('craftsman', 'user')},
            },
        ),
    ]
