# Generated by Django 5.2.1 on 2026-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_teaminvite_craftsmanmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='intasend_invoice_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
