# Generated by Django 5.2.1 on 2026-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_jobrequest_intasend_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='wallet_id',
            field=models.IntegerField(blank=True, help_text='jay4t.org gateway wallet ID — set at first profile save', null=True),
        ),
    ]
