# Generated by Django 5.2.1 on 2025-06-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_craftsman_primary_service_craftsman_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='primary_service',
            field=models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Roofing', 'Roofing'), ('Welding', 'Welding'), ('Tiling', 'Tiling'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Masonry', 'Masonry'), ('AC Repair', 'AC Repair'), ('Woodwork', 'Woodwork'), ('Auto Repair', 'Auto Repair')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='service',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Roofing', 'Roofing'), ('Welding', 'Welding'), ('Tiling', 'Tiling'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Masonry', 'Masonry'), ('AC Repair', 'AC Repair'), ('Woodwork', 'Woodwork'), ('Auto Repair', 'Auto Repair')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Roofing', 'Roofing'), ('Welding', 'Welding'), ('Tiling', 'Tiling'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Masonry', 'Masonry'), ('AC Repair', 'AC Repair'), ('Woodwork', 'Woodwork'), ('Auto Repair', 'Auto Repair')], max_length=255),
        ),
    ]
