# Generated by Django 5.2.1 on 2026-03-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_craftsman_wallet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='intasend_invoice_id',
        ),
    ]
