# Generated by Django 5.2.1 on 2025-06-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_craftsman_primary_service_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
