# Generated by Django 5.2.1 on 2026-03-31 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_jobrequest_intasend_invoice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='slug',
        ),
        migrations.AddField(
            model_name='craftsman',
            name='availability_status',
            field=models.CharField(choices=[('online', 'Online'), ('busy', 'Busy')], default='online', max_length=10),
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('service', models.CharField(blank=True, choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Roofing', 'Roofing'), ('Welding', 'Welding'), ('Tiling', 'Tiling'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Masonry', 'Masonry'), ('AC Repair', 'AC Repair'), ('Woodwork', 'Woodwork'), ('Auto Repair', 'Auto Repair')], max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='api.craftsman')),
                ('job_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='api.jobrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityNotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_notifications', to=settings.AUTH_USER_MODEL)),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='api.craftsman')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('client', 'craftsman')},
            },
        ),
    ]
