# Generated by Django 5.2.1 on 2026-03-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_craftsman_slug_craftsman_availability_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='wallet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
