# Generated by Django 5.2.1 on 2026-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_craftsman_last_seen_craftsman_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_pct', models.FloatField(default=10)),
                ('min_budget', models.IntegerField(default=500)),
                ('max_budget', models.IntegerField(default=500000)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20)),
                ('enabled_services', models.JSONField(default=list)),
                ('enabled_locations', models.JSONField(default=list)),
                ('notifications', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
    ]
