# Generated by Django 5.2.1 on 2025-06-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRequest',
        ),
    ]
