# Generated by Django 5.2.1 on 2025-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_jobrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
