# Generated by Django 5.2.1 on 2025-09-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_craftsman_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='slug',
        ),
    ]
