# Generated by Django 5.2.1 on 2025-10-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_review_created_at_review_job_and_more'),
    ]

    operations = [
    ]
