# Generated by Django 5.2.1 on 2026-03-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_role',
            field=models.CharField(choices=[('client', 'Client'), ('craftsman', 'Craftsman')], default='craftsman', help_text='The role the user is currently browsing as (can be switched).', max_length=20),
        ),
    ]
