# Generated by Django 5.2.1 on 2025-06-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client'),
        ('api', '0030_delete_jobrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
