# Generated by Django 5.2.1 on 2025-05-22 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_craftsman_status_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='productName',
            field=models.CharField(default='Default Product Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='craftsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.craftsman'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default', upload_to='products/'),
        ),
    ]
