# Generated by Django 5.2.1 on 2025-05-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_upload_path/'),
        ),
    ]
