# Generated by Django 5.2.1 on 2025-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_craftsman_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
