# Generated by Django 5.2.1 on 2025-06-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_craftsman_latitude_craftsman_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsman',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='longitude',
        ),
    ]
