# Generated by Django 5.2.1 on 2025-06-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_craftsman_latitude_remove_craftsman_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='craftsmen/gallery/')),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.craftsman')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.craftsman')),
            ],
        ),
    ]
