# Generated by Django 5.2.1 on 2025-06-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_craftsman_company_name_craftsman_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='services/')),
                ('craftsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.craftsman')),
            ],
        ),
    ]
