# Generated by Django 5.2.1 on 2025-06-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_service_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsman',
            name='primary_service',
            field=models.CharField(blank=True, choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('masonry', 'Masonry'), ('tiling', 'Tiling'), ('roofing', 'Roofing'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/'),
        ),
    ]
