# Generated by Django 5.2.1 on 2025-06-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client'),
        ('api', '0026_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
