# Generated by Django 5.2.1 on 2025-06-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_contactmessage_subject_alter_contactmessage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
