# Generated by Django 5.2.1 on 2025-06-27 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_delete_jobrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Roofing', 'Roofing'), ('Welding', 'Welding'), ('Tiling', 'Tiling'), ('Interior Design', 'Interior Design'), ('Landscaping', 'Landscaping'), ('Masonry', 'Masonry'), ('AC Repair', 'AC Repair'), ('Woodwork', 'Woodwork'), ('Auto Repair', 'Auto Repair')], max_length=50)),
                ('custom_service', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isUrgent', models.BooleanField(default=False)),
                ('media', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
